// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // IMPORTANT: Update these values with your Firebase project credentials
    // You can get these from Firebase Console -> Project Settings
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ8stneJp-tq2SZ2Cf-DyB2FrlPPvHGxg',
    appId: '1:594108323606:web:placeholder',
    messagingSenderId: '594108323606',
    projectId: 'fitness-74404',
    authDomain: 'fitness-74404.firebaseapp.com',
    storageBucket: 'fitness-74404.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ8stneJp-tq2SZ2Cf-DyB2FrlPPvHGxg',
    appId: '1:594108323606:android:2f343926227698c539a237',
    messagingSenderId: '594108323606',
    projectId: 'fitness-74404',
    databaseURL: 'https://fitness-74404.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxNSqLkHypPFo5xyClv_AeIc3owo0V1a8',
    appId: '1:594108323606:ios:731bd79eb9de6e2139a237',
    messagingSenderId: '594108323606',
    projectId: 'fitness-74404',
    databaseURL: 'https://fitness-74404.firebaseio.com',
    iosBundleId: 'com.example.resumeBuilder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxNSqLkHypPFo5xyClv_AeIc3owo0V1a8',
    appId: '1:594108323606:ios:731bd79eb9de6e2139a237',
    messagingSenderId: '594108323606',
    projectId: 'fitness-74404',
    databaseURL: 'https://fitness-74404.firebaseio.com',
    iosBundleId: 'com.example.resumeBuilder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ8stneJp-tq2SZ2Cf-DyB2FrlPPvHGxg',
    appId: '1:594108323606:web:placeholder',
    messagingSenderId: '594108323606',
    projectId: 'fitness-74404',
    authDomain: 'fitness-74404.firebaseapp.com',
    storageBucket: 'fitness-74404.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAJ8stneJp-tq2SZ2Cf-DyB2FrlPPvHGxg',
    appId: '1:594108323606:web:placeholder',
    messagingSenderId: '594108323606',
    projectId: 'fitness-74404',
    authDomain: 'fitness-74404.firebaseapp.com',
    storageBucket: 'fitness-74404.firebasestorage.app',
  );
}
